//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string fecha { get; set; }
        public string cliente { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public string numero { get; set; }
        public int empresa_id { get; set; }
        public Nullable<int> estatus { get; set; }
        public int tipo { get; set; }
        public string ruc { get; set; }
        public string direccion { get; set; }
        public string empresa { get; set; }
    }
}
