//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factura.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class users
    {
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email Requerido")]
        public string email { get; set; }
        
        public string nombres { get; set; }
        public System.DateTime created_at { get; set; }
        public int rol_id { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password Requerido")]
        public string password { get; set; }
       
        public int id { get; set; }
        public string LoginErrorMessage { get; set; }
        public int active { get; set; }
    }
}
